# Generated by Django 3.2.7 on 2021-09-09 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=5, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('sit_count', models.IntegerField(blank=True, default=0, null=True)),
                ('max_sit', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('register', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
